server:
  port: 7071

spring:
  application:
    name: Bender Bot
    short-io:
        url: https://api.short.io
        token: ${SHORT_IO_TOKEN}
        domain-id: ${SHORT_IO_DOMAIN_ID}

  datasource:
    url: jdbc:mysql://localhost:3303/bender_bot?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Argentina/Cordoba
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com:
      telegram:
        bot: ${LOGGING_LEVEL_COM_TELEGRAM_BOT:INFO}
    org:
      springframework: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK:WARN}
      hibernate:
        SQL: ${LOGGING_LEVEL_ORG_HIBERNATE_SQL:DEBUG}

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}
    creator: ${TELEGRAM_BOT_CREATOR}
