server:
  port: 7071

spring:
  application:
    name: Bender Bot
    short-io:
        url: https://api.short.io
        token: ${SHORT_IO_TOKEN}
        domain-id: ${SHORT_IO_DOMAIN_ID}
        link-id:
          bender: ${SHORT_IO_BENDER_LINK_ID}
          immich: ${SHORT_IO_IMMICH_LINK_ID}
          nextcloud: ${SHORT_IO_NEXTCLOUD_LINK_ID}
          spliit: ${SHORT_IO_SPLIIT_LINK_ID}
          pingvin-share: ${SHORT_IO_PINGVIN_SHARE_LINK_ID}

  datasource:
    url: jdbc:mysql://localhost:3303/bender_bot?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Argentina/Cordoba
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com:
      telegram:
        bot: ${LOGGING_LEVEL_COM_TELEGRAM_BOT:INFO}
    org:
      springframework: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK:WARN}
      hibernate:
        SQL: ${LOGGING_LEVEL_ORG_HIBERNATE_SQL:DEBUG}
        type:
          descriptor:
            sql:
              BasicBinder: ${LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL_BASICBINDER:TRACE}

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}
    creator: ${TELEGRAM_BOT_CREATOR}



